In [16]:
# № 1.3.1

import numpy as np

array = np.zeros((8, 8))
array[0::2, 1::2] = 1
array[1::2, 0::2] = 1
print(array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [17]:
# № 1.3.2

import numpy as np

array = np.zeros((5, 5))
array += np.arange(5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [18]:
# № 1.3.3

import numpy as np

array = np.random.random((3, 3, 3))
print(array)

[[[0.38810951 0.85776159 0.21113346]
  [0.39086005 0.43403633 0.6699942 ]
  [0.10718672 0.07176641 0.29269191]]

 [[0.62772623 0.01951708 0.43355395]
  [0.87057334 0.63822577 0.34115814]
  [0.78720831 0.61912426 0.7430725 ]]

 [[0.20464526 0.34411731 0.72549033]
  [0.73719073 0.8952056  0.54003654]
  [0.64868223 0.17515071 0.63319134]]]


In [19]:
# № 1.3.4

import numpy as np

array = np.zeros((7, 7))
array[:, [0, -1]] = 1
array[[0, -1], :] = 1
print(array)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [20]:
# № 1.3.5

import numpy as np

array = np.array([2, 1, 5, 3, 7, 4, 6, 8, 9])
array = np.sort(array)[::-1]
print(array)

[9 8 7 6 5 4 3 2 1]


In [32]:
# № 1.3.6

import numpy as np

array = np.random.random((3, 5))
print("Array:", "\n", array)
shape = np.shape(array)
size = np.size(array)
dimension = np.ndim(array)
print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)

Array: 
 [[0.88063552 0.81044067 0.39264389 0.19684827 0.77895575]
 [0.3255678  0.19073848 0.98641038 0.94549513 0.38116013]
 [0.30418664 0.06908344 0.54159473 0.36729678 0.45894093]]
Shape: (3, 5)
Size: 15
Dimension: 2


In [3]:
# № 2.3.1

import pandas as pd
import math as m

print("Enter coordinates of the first point:")
x1, y1, = map(int, input().split())
print("Enter coordinates of the second point:")
x2, y2, = map(int, input().split())
x = pd.Series({'a': x1, 'b': x2})
y = pd.Series({'a': y1, 'b': y2})
distance = m.sqrt((x['a'] - x['b']) ** 2 + (y['a'] - y['b']) ** 2)
print("Euclidean distance =", distance)

Enter coordinates of the first point:
6 8
Enter coordinates of the second point:
3 4
Euclidean distance = 5.0


In [7]:
# № 2.3.2

import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/FMLPDA_Table4_3.csv'
dataframe = pd.read_csv(url)
dataframe

stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer
5    True     steep   highest    conifer
6    True     steep      high  chapparal

In [12]:
# № 2.3.3

import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/FMLPDA_Table4_3.csv'
dataframe = pd.read_csv(url)
display(
    dataframe.head(3),
    dataframe.tail(2),
    dataframe.shape,
    dataframe.describe(),
    dataframe.iloc[1:5],
    dataframe.loc[1:5],
    dataframe[dataframe['elevation'] == 'high'])

stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian

stream  slope elevation vegetation
5    True  steep   highest    conifer
6    True  steep      high  chapparal

(7, 4)

stream  slope elevation vegetation
count       7      7         7          7
unique      2      3         4          3
top      True  steep      high  chapparal
freq        4      5         3          3

stream     slope elevation vegetation
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer

stream     slope elevation vegetation
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer
5    True     steep   highest    conifer

stream  slope elevation vegetation
0   False  steep      high  chapparal
4   False   flat      high    conifer
6    True  steep      high  chapparal

In [1]:
# № 3.3.2

import pandas as pd
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
dataframe[["sepal_length_cm"]] = preprocessing.MinMaxScaler().fit_transform(dataframe[["sepal_length_cm"]])
dataframe[["sepal_width_cm"]] = preprocessing.StandardScaler().fit_transform(dataframe[["sepal_width_cm"]])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]